name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name != 'pull_request' || github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject commit SHA into HTML
        run: |
          COMMIT_SHA=${{ github.sha }}
          echo "Injecting commit SHA: $COMMIT_SHA"
          sed -i "s|<!-- COMMIT_SHA -->|Commit: $COMMIT_SHA|" ./index.html

      - name: Build (if needed)
        run: |
          echo "No build step required for static HTML site."

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"           
          api_location: ""            
          output_location: "/"        
